name: Sync Douban Movies to Notion

on:
  workflow_dispatch:
    inputs:
      douban_urls:
        description: "多个豆瓣电影链接，逗号分隔"
        required: true
        default: "https://movie.douban.com/subject/1292052/,https://movie.douban.com/subject/1293172/"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write input URLs to file and run sync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          echo "===== 原始输入 ====="
          echo "${{ github.event.inputs.douban_urls }}"

          echo "${{ github.event.inputs.douban_urls }}" | tr -d '\r' > urls.txt
          echo "===== 写入的 urls.txt 内容 ====="
          cat urls.txt

          python fetch_douban_movie.py urls.txt
          cat urls.txt

          python fetch_douban_movie.py urls.txt
